
---
apiVersion: v1
kind: Service
metadata:
  name: expedition-webui-service
  namespace: blockchain
spec:
  selector:
    app: expedition-webui
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000