apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bc-ebs-claim
  namespace: blockchain
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: bc-ebs-sc
  resources: 
    requests:
      storage: 1Gi