apiVersion: v1
kind: Service
metadata:
  name: geth-poa-node-svc
  namespace: blockchain
  labels:
    app: geth-poa-gethnode
spec:
  selector:
    app: geth-poa-gethnode
  ports:
  - name: discovery
    port: 30301
    protocol: UDP
  - name: discovtcp
    port: 30301
    protocol: TCP
  - name: http
    port: 8545
    protocol: TCP