apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-poa-node-configmap
  namespace: blockchain
  labels:
    app: geth-poa-gethnode
data:
  node.datadir: /data/gethpoa/

---

apiVersion: v1
kind: Secret
metadata:
  name:  geth-poa-node-secret
  namespace: blockchain
type: Opaque
data:
   gethAccountCred: smskksksksksww23==
